spring:
  mvc:
    #配置jsp目录
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  #配置数据库
  datasource:
    tomcat:
      initial-size: 5
      min-idle: 5
      max-active: 15
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.jeffy.demo.eneity

#日志输出配置
logging:
  config: classpath:logback.xml


#配置jsp热部署
server:
  servlet:
    jsp:
      init-parameters:
        development: true
    session:
      #设置session过期时间(12小时)
      timeout: 43200s